"""Initial schema

Revision ID: a401aee66d8a
Revises: 
Create Date: 2026-02-16 05:13:26.431193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a401aee66d8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('roadmaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.String(length=500), nullable=False),
    sa.Column('time_available', sa.String(length=100), nullable=False),
    sa.Column('current_level', sa.String(length=100), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('notification_time', sa.String(length=10), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_created_at'), 'roadmaps', ['created_at'], unique=False)
    op.create_index(op.f('ix_roadmaps_user_id'), 'roadmaps', ['user_id'], unique=False)
    op.create_table('completed_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('roadmap_id', sa.String(length=36), nullable=True),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completed_items_item_id'), 'completed_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_completed_items_roadmap_id'), 'completed_items', ['roadmap_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_completed_items_roadmap_id'), table_name='completed_items')
    op.drop_index(op.f('ix_completed_items_item_id'), table_name='completed_items')
    op.drop_table('completed_items')
    op.drop_index(op.f('ix_roadmaps_user_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_created_at'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
